apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-ai-poi.fullname" . }}
  labels:
    {{- include "go-ai-poi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.pprofPort }}
      targetPort: pprof
      protocol: TCP
      name: pprof
  selector:
    {{- include "go-ai-poi.selectorLabels" . | nindent 4 }}